name: simple CI

on:
  push:
    branches: ["main"]

jobs:
  run:
    run-on:ubuntu-latest

    setups:
      -name:checkout
       user:actions/python@v3

       -name:run ids-script
        run: |
          chmod +x ids-script.sh
          ./ids-script.sh
